### ISSUE TITLE
Is jaxedit written all in javascript? why not wrap it as a lib?

### ISSUE THREAD

**Issue by xu-song** [zohooo/jaxedit#10]
Can u share a doc about "how to setup a mini-system for tex visualization or markdown visualization "?

It would be better if `jaxedit` can be wrapped as a lib, like `mathjax`,  rather than an online demo.

**Comment by hellohappy0** [comment]
The follow content make it Enter the Dead Cycle？
but I do not know why
% -*- coding: utf-8 -*-
\documentclass

% https://github.com/zohooo/epyt
% \usetheme

\newtheorem

\begin

\title{Online LaTeX Editor}
\author{JaxEdit Project}
\date{July 3rd, 200012}

\begin
\titlepage
\end

\section[Introduction]{Long Introduction}

\begin
We have the Cauchy-Schwarz inequality:
  \[ \left( \sum_{k=1}^n a_k b_k \right)^2 \leq \left( \sum_{k=1}^n a_k^2 \right) \left( \sum_{k=1}^n b_k^2 \right) \]
where $a_k$ and $b_k$ are real numbers, for any $k$.
\end

\section

\begin
\begin
If we have the following conditions:
\begin
\item $f(x)$ is continuous on $[a,b]$,
\item $f(a)$ and $f(b)$ are of different signs,
\end
Then there exists a point $\xi\in(a,b)$ such that $f(\xi)=0$.
\end
\end

\end

**Comment by zohooo** [comment]
See https://zohooo.github.io/jaxedit/manual/parser.html
