### ISSUE TITLE
Is it possible to share JaxEdit and others and see their change in real-time?

### ISSUE THREAD

**Issue by jasjuang** [zohooo/jaxedit#7]
Hi, I am wondering whether it is possible to share JaxEdit and others and see their change in real-time.

I opened a new JaxEdit document, and shared it. However, when I copy the link into another computer and open it to make some changes, I am not able to see the change at the original computer. Am I doing anything wrong?

**Comment by zohooo** [comment]
At present, it is impossible to see changes in real time.

**Comment by jasjuang** [comment]
Thanks for letting me know
