### ISSUE TITLE
Inserting image/video/code block

### ISSUE THREAD

**Issue by fa93hws** [zohooo/jaxedit#9]
Hi
I am not sure how to add image, video or code block with jaxedit.
HTML tags seems to be blocked.
Thanks

**Comment by zohooo** [comment]
I am sorry it is impossible in JaxEdit at present.
For image/video/code block, it is better to use markdown but not latex.

**Comment by fa93hws** [comment]
Many thanks for your reply.
I also notice that you have a project called JaxMark but the demo page seems not working (https://zohooo.github.io/jaxmark/)
I am wondering does that site support aligned tag in latex?
Many thanks for your reply.

**Comment by zohooo** [comment]
JaxMark fixed.
